### PR TITLE
Switch to Elogram

### PR DESCRIPTION
**Pull request by vinkla**
The old Instagram package is dead. Instead we're going to move to the amazing [Elogram](https://github.com/larabros/elogram) by @hassankhan.

### CODE REVIEW

**Comment by vinkla** [comment]
@hassankhan out of curiosity, why is the client class final?

**Comment by hassankhan** [comment]
Because I didn't think there'd be any reason to extend it, anything you need to change/set **should** be doable through the constructor. 

Is there something I might be missing?

**Comment by florianbeer** [comment]
Neat! Elogram looks really well done. Shame that I just worked on updating the other package. Seems like I'll do another refactor tomorrow to integrate with this one.

@vinkla Are you going to hook into Laravel's session handling? http://elogram.readthedocs.org/en/latest/developers.html#nativesessionstore

**Comment by hassankhan** [comment]
Hi @florianbeer, thanks for the kind words!

To answer your question to @vinkla, yes, I'm pretty sure it will have to be integrated with Laravel, much like Facebook's SDK.

**Comment by vinkla** [comment]
@hassankhan thanks for explaining.


@florianbeer yeah, I'll look into that. Thanks for pointing it out!

**Comment by hassankhan** [comment]
Just had a look at the Travis test results, trying to see if there's a way I can help without having to remove the `final` statement.

Does @GrahamCampbell's package automatically mock container dependencies or something? Seems pretty cool, did not know about it.

Checking [Mockery's docs](http://docs.mockery.io/en/latest/reference/final_methods_classes.html), maybe try instantiating the `Client` and then passing to `Mockery::mock()`? According to the docs, it **should** work

**Comment by vinkla** [comment]
@hassankhan nope, didn't work. Thanks for reaching out though.

**Comment by vinkla** [comment]
@hassankhan the tests pass now. Now it is only the custom session handling left. Anything else we need to think of before going further?

**Comment by hassankhan** [comment]
Yep, pretty sure you only need to replace the session handling :+1:

**Comment by vinkla** [comment]
@hassankhan okay, good :+1:

**Comment by vinkla** [comment]
@hassankhan except the `session_storage` parameter what other parameters does the `$options` array allow?

**Comment by hassankhan** [comment]
Awesome work :smile: thanks for choosing Elogram!

**Comment by vinkla** [comment]
Thanks:)

**Pull request merged**
